sudo: true
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

install: 
  - "sudo apt-get install pandoc"
  - "pip install -r requirements.txt"
  
script: 
  - "python setup.py install"
